exports.translations = {
 'nav.itech':['iTech','iTech','iTech'],
 'title.itech':['iTech | Mirza Dugopoljac','iTech | Mirza Dugopoljac','iTech | Mirza Dugopoljac'],
 'it.label':['DESIGN MEETS TECHNOLOGY','TASARIM TEKNOLOJİYLE BULUŞUYOR','DIZAJN SUSREĆE TEHNOLOGIJU'],
 'it.title':['Ideas into<br><em>real-world impact.</em>','Fikirlerden<br><em>gerçek etkiye.</em>','Od ideje do<br><em>stvarnog utjecaja.</em>'],
 'it.intro':['iTech is an international R&D team working across software, electronics and intelligent systems. I contribute to the team in design.','iTech; yazılım, elektronik ve akıllı sistemler üzerinde çalışan uluslararası bir Ar-Ge ekibidir. Ekibe tasarım alanında katkı sağlıyorum.','iTech je međunarodni istraživačko-razvojni tim koji radi na softveru, elektronici i inteligentnim sistemima. Timu doprinosim kroz dizajn.'],
 'it.visit':['Explore itechtr.com ↗','itechtr.com’u keşfet ↗','Istraži itechtr.com ↗'],
 'it.work':['Discover the projects ↓','Projeleri keşfet ↓','Otkrij projekte ↓'],
 'it.index':['01 / SELECTED DEVELOPMENT PROJECTS','01 / GELİŞTİRİLEN SEÇİLİ PROJELER','01 / ODABRANI PROJEKTI U RAZVOJU'],
 'it.heading':['Three directions.<br>One curious team.','Üç yön.<br>Meraklı bir ekip.','Tri pravca.<br>Jedan radoznao tim.'],
 'it.status':['IN DEVELOPMENT','GELİŞTİRME AŞAMASINDA','U RAZVOJU'],
 'it.glasses':['Smart eyewear exploring AI-assisted accessibility and everyday interaction. The family includes Vision, Lite and Pro concepts.','Yapay zekâ destekli erişilebilirlik ve günlük etkileşimi araştıran akıllı gözlükler. Ürün ailesi Vision, Lite ve Pro konseptlerini içeriyor.','Pametne naočale koje istražuju pristupačnost uz AI i svakodnevnu interakciju. Porodica uključuje Vision, Lite i Pro koncepte.'],
 'it.strix':['An agricultural platform combining AI, sensing and autonomous navigation to support more precise use of resources.','Kaynakların daha hassas kullanımını desteklemek için yapay zekâ, algılama ve otonom navigasyonu birleştiren tarım platformu.','Poljoprivredna platforma koja povezuje AI, senzore i autonomnu navigaciju za preciznije korištenje resursa.'],
 'it.sobit':['A UAV research project exploring safer landmine detection through intelligent sensing, with a humanitarian focus.','İnsani amaçlarla, akıllı algılama üzerinden daha güvenli mayın tespitini araştıran İHA projesi.','Istraživački projekat bespilotne letjelice za sigurnije otkrivanje mina pomoću inteligentnih senzora, s humanitarnim fokusom.'],
 'it.more':['Explore on iTech ↗','iTech’te incele ↗','Istraži na iTech stranici ↗'],
 'it.note':['Project descriptions and visuals: iTech. These are development projects; visit the official site for current information.','Proje açıklamaları ve görseller: iTech. Projeler geliştirme aşamasındadır; güncel bilgi için resmî siteyi ziyaret edin.','Opisi i vizuali projekata: iTech. Projekti su u razvoju; posjetite službenu stranicu za aktuelne informacije.'],
 'it.end':['Meet the team.<br><em>Follow the work.</em>','Ekiple tanış.<br><em>Çalışmaları takip et.</em>','Upoznaj tim.<br><em>Prati njihov rad.</em>'],
 'it.pause':['Pause animation','Animasyonu durdur','Pauziraj animaciju'],
 'it.resume':['Resume animation','Animasyonu sürdür','Nastavi animaciju']
};
exports.body=({tr})=>`<div class="itech-page"><header class="itech-hero shell"><div class="itech-intro">${tr('it.label','p','micro')}<div class="itech-wordmark">iTech<span>R&D</span></div>${tr('it.title','h1')}${tr('it.intro','p','itech-description')}<div class="actions"><a class="btn primary" href="https://itechtr.com/">${tr('it.visit')}</a><a class="text-link" href="#itech-projects">${tr('it.work')}</a></div></div><div class="itech-instrument"><div class="itech-orbits" aria-hidden="true"><i></i><i></i><i></i><div class="itech-core">i<span>Tech</span></div><span class="orbit-point p1">AI</span><span class="orbit-point p2">DESIGN</span><span class="orbit-point p3">R&D</span></div><div class="instrument-bottom"><span class="micro">SOFTWARE / HARDWARE / INTELLIGENCE</span><button id="itech-motion" aria-pressed="false" data-i18n="it.pause">Pause animation</button></div></div></header><section class="itech-projects shell" id="itech-projects">${tr('it.index','p','micro')}${tr('it.heading','h2')}${[
 ['01','iGLASSES','AI / ACCESSIBILITY','Iglasses-visionn.png','it.glasses'],
 ['02','STRIX','AGRICULTURE / AUTONOMY','strix-car.png','it.strix'],
 ['03','SOBIT','UAV / HUMANITARIAN','sobit-drone.png','it.sobit']
].map(([n,name,category,img,key])=>`<article class="itech-project"><div class="itech-visual"><span class="micro">IT—${n} / ${category}</span><img src="https://itechtr.com/img/projects/${img}" alt="${name} — iTech project visualization" loading="lazy" width="900" height="650"><span class="visual-cross" aria-hidden="true">+</span></div><div class="itech-project-copy"><div class="itech-status">${tr('it.status','span','micro')}</div><h3>${name}</h3>${tr(key,'p')}<a class="text-link" href="https://itechtr.com/">${tr('it.more')}</a></div></article>`).join('')}${tr('it.note','p','itech-source')}</section><section class="itech-outro shell"><span class="micro">02 / ITECHTR.COM</span>${tr('it.end','h2')}<a class="itech-exit" href="https://itechtr.com/">${tr('it.visit')}<span aria-hidden="true">↗</span></a></section></div>`;
